### ISSUE TITLE
improve documentation, add simple examples starting from require part

### ISSUE THREAD

**Issue by revelt** [tenbits/Regex#1]
Documentation is missing very basic examples how to use this library, and _Named Groups_ section doesn't include the `require` part. Also, I suspect that there is a type in `mach`:

```
var rgx = new Regex('Name:\\s*(?<name>\\w+)');
var match = rgx.mach('My Name: Baz');
equals(match.groups.name, 'Baz');
```

You can't test the above thing by pasting into [tonicdev.com](https://tonicdev.com/npm/atma-regex) either, and it's unclear what to do after requiring `atma-regex`.

The unique feature of this library is _negative lookbehind_ and masses can't tap into it at the moment because of poor documentation.

**Comment by tenbits** [comment]
Hi Roy, I have update the  documentation a little bit, and added a code snippet to test on tonicdev.com. Additional code and samples you can see in [**.test](https://github.com/tenbits/Regex/tree/master/test)

_Should you have any questions or finds some bugs, please open further issues_

**Comment by boucher** [comment]
Hey @tenbits, Not sure if you already know this, but you can customize the example that shows up on the npm/tonic page if you want. (https://tonicdev.uservoice.com/knowledgebase/articles/765846-how-do-i-customize-the-example-for-my-npm-package)

**Comment by tenbits** [comment]
Hi @boucher , thanks for pointing me on this. I have added also the tonics example file. Works perfect)
